cohorts:
    - ACC
    - BRCA
    - COAD
    - HNSC
    - PRAD
    - SKCM

methods:
    - genenet
    - aracne
    - TFbinding
    - mrnetb.wrap
    - mutrank.wrap
    - pcit.wrap
    - clr.wrap
    - mrnet.wrap
    - aracne.wrap
    - c3net.wrap
    - zscore.wrap
    - Genie3
    - Genie3+TF
#    - Tigress
    - Tigress+TF

set_enrichment:
    - focal
    - aneup
    - purity

correction:
    - naive
#    - copycor

method_str:
    - genenet: GeneNet
    - aracne: ARACNe
    - TFbinding: TF binding
    - mrnetb.wrap: MRNETb
    - mutrank.wrap: MRNET
    - pcit.wrap: PCIT
    - clr.wrap: CLR
    - mrnet.wrap: MRNET
    - aracne.wrap: ARACNe
    - c3net.wrap: C3NET
    - zscore.wrap: Z-score
    - Genie3: GENIE3
    - Genie3+TF: GENIE3
#    - Tigress: TIGRESS
    - Tigress+TF: TIGRESS

has_tf:
    - aracne
    - Genie3+TF
    - Tigress+TF
