cohorts:
    - ACC
    - BRCA
    - COAD
    - HNSC
    - PRAD
    - SKCM

methods:
    - genenet
    - aracne
    - TFbinding
    - mrnetb.wrap
    - mutrank.wrap
    - pcit.wrap
    - clr.wrap
    - mrnet.wrap
    - aracne.wrap
    - c3net.wrap
    - zscore.wrap
    - Genie3
    - Genie3+TF
    - Tigress
    - Tigress+TF

set_enrichment:
    - focal
    - aneup
    - purity

correction:
    - naive
    - copycor
