configfile: "../config.yaml"

subworkflow data:
    workdir: "../data"
    snakefile: "../data/Snakefile"

subworkflow net:
    workdir: "../networks"
    snakefile: "../networks/Snakefile"

rule all:
    input:
        expand("plot_{region}.pdf", region=config['set_enrichment'])

rule plot:
    input:
        rscript = "plot_{region}.r",
        infile = "merge.RData"
    output:
        plotfile = "plot_{region}.pdf"
    shell:
        "Rscript {input.rscript}"
            " --infile {input.infile}"
            " --region {wildcards.region}"
            " --plotfile {output.plotfile}"

rule merge:
    input:
        rscript = "merge.r",
        infiles = expand("{region}_{method}/{correction}/{cohort}.RData",
                region=config['set_enrichment'], method=config['methods'],
                correction=config['correction'], cohort=config['cohorts'])
    output:
        outfile = "merge.RData"
    shell:
        "Rscript {input.rscript}"
            " --outfile {output.outfile}"
            " {input.infiles}"

rule fet:
    input:
        rscript = "check_set_enrichment.r",
        network = net("{method}/{correction}/{cohort}.RData"),
        sets = data("{region}.RData")
    output:
        result = "{region}_{method}/{correction}/{cohort}.RData"
    shell:
        "Rscript {input.rscript}"
            " --cohort {wildcards.cohort}"
            " --sets {input.sets}"
            " --method {wildcards.method}"
            " --network {input.network}"
            " --outfile {output.result}"
