configfile: "../config.yaml"

mem = {
    'aracne' : 10240,
    'genenet' : 102400
}

rule all:
    input:
        expand("{method}/{cohort}.RData", method=config['methods'], cohort=config['cohorts'])

rule network:
    input:
        rscript = "{method}.r"
    output:
        data = "{method}/{cohort}.RData"
    resources:
        mem = lambda wc: mem[wc.method],
        walltime = 720
    shell:
        "Rscript {input.rscript}"
            " --cohort {wildcards.cohort}"
            " --method {wildcards.method}"
            " --outfile {output.data}"
