configfile: "../config.yaml"

subworkflow data:
    workdir: "../data"
    snakefile: "../data/Snakefile"

subworkflow net:
    workdir: "../networks"
    snakefile: "../networks/Snakefile"

rule all:
    input:

rule merge:
    input:
        rscript = "merge.r",
        infiles = expand("{region}_{method}/{cohort}.RData", region=config['regions'],
                method=config['methods'], cohort=config['cohorts'])
    output:
        outfile = "merge.RData",
        plotfile = "merge.pdf"
    shell:
        "Rscript {input.rscript}"
            " --outfile {output.outfile}"
            " --plotfile {output.plotfile}"
            " {input.infiles}"

rule fet:
    input:
        rscript = "check_region.r",
        network = net("{method}/{cohort}.RData"),
        regions = data("{region}.RData")
    output:
        result = "{region}_{method}/{cohort}.RData"
    shell:
        "Rscript {input.rscript}"
            " --cohort {wildcards.cohort}"
            " --regions {input.regions}"
            " --method {wildcards.method}"
            " --network {input.network}"
            " --outfile {output.result}"
