datasrc = {
    'focal' : 'TableS2D.xlsx',
    'aneup' : 'dummy',
    'purity' : 'dummy',
    'immune' : '1-s2.0-S1074761318301213-mmc2.xlsx',
    'tfs' : 'dummy'
}

rule all:
    input:
        "meta.RData", "tfs.RData"

rule merge:
    input:
        rscript = "merge.r",
        data = expand("{obj}.RData", obj=['focal', 'aneup', 'purity', 'immune'])
    output:
        data = "meta.RData"
    shell:
        "Rscript {input.rscript} --outfile {output.data} {input.data}"

rule obj:
    input:
        rscript = "{obj}.r",
        data = lambda wc: datasrc[wc.obj]
    output:
        data = "{obj}.RData"
    shell:
        "Rscript {input.rscript} --infile {input.data} --outfile {output.data}"

rule amps:
    output:
        "TableS2D.xlsx"
    shell:
        "wget https://www.cancerrxgene.org/gdsc1000/GDSC1000_WebResources//Data/suppData/TableS2D.xlsx"

rule immune:
    output:
        "1-s2.0-S1074761318301213-mmc2.xlsx"
    shell:
        "wget https://ars.els-cdn.com/content/image/1-s2.0-S1074761318301213-mmc2.xlsx"
